### ISSUE TITLE
最近 cookies 频繁失效

### ISSUE THREAD

**Issue by zanderzhng** [iambus/xunlei-lixian#446]
和不在大陆有关系吗。

**Comment by ibegyourpardon** [comment]
@zanderzhng 不是应该有个.xunlei.cookies 的文件吗？都写在里面，想失效也失不了...

**Comment by zanderzhng** [comment]
@ibegyourpardon 提示 not logged in，然后得手动删掉那个文件才能再登陆。现在用回 config 里放明文密码的方式了。
